default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: dnd5e_api_development

test:
  <<: *default
  database: dnd5e_api_test

production:
  <<: *default
  database: dnd5e_api_production
